---
# Tracking steps to run
run_advection: 0
# Segment and identify clouds 
run_idclouds: 1
# Track single consecutive cloudid files
run_tracksingle: 0
# Run trackig for all files
run_gettracks: 0
# Calculate final statistics
run_finalstats: 0
# Create maps of cells
run_labelcell: 0
# Start/end date and time
startdate: '20190208.0000'
enddate: '20190209.0000'
# Parallel processing set up
run_parallel: 0
nprocesses: 30
# Data source, description
datasource: WRF
datadescription: WRF
databasename: convmask_
# Working directory for the tracking data
root_path: "/global/cscratch1/sd/barb672/lasso/"
# Input files directory
clouddata_path: "/global/cscratch1/sd/barb672/lasso/20190208/gefs1deg_en13/run20190208_thom_k150ptop11_dzbot25_dzsts1.05_dzstu1.05/"
# Drift (advection) file directory
# driftfile: "/lustre/or-hydra/cades-arm/proj-shared/iclass/cacti/radar_processing/taranis_corcsapr2cfr_advectionM1.c1/csapr2_500m_advection_full_campaign.nc"
# Terrain file 
terrain_file: "/global/cscratch1/sd/barb672/lasso/20190208/gefs1deg_en13/run20190208_thom_k150ptop11_dzbot25_dzsts1.05_dzstu1.05/subset/wrfout_subset_d02_2019-02-08_02_30_00.nc"
