---
# Tracking steps to run
run_advection: 0
# Segment and identify clouds 
run_idclouds: 1
# Track single consecutive cloudid files
run_tracksingle: 1
# Run trackig for all files
run_gettracks: 1
# Calculate final statistics
run_finalstats: 1
# Create maps of cells
run_labelcell: 1
# Start/end date and time
startdate: '20181015.0000'
enddate: '20190303.0000'
# Parallel processing set up
run_parallel: 1
nprocesses: 30
# Data source, description
datasource: CSAPR2
datadescription: COR
databasename: taranis_corcsapr2cfrppiqcM1_convmask.c1.
# Working directory for the tracking data
root_path: "/global/cscratch1/sd/feng045/iclass/cacti/arm/csapr/taranis_corcsapr2cfrppiqcM1_celltracking.c1.new/"
# Input files directory
clouddata_path: "/global/cscratch1/sd/feng045/iclass/cacti/arm/csapr/taranis_corcsapr2cfrppiqcM1_gridded_convmask.c1/"
# Drift (advection) file directory
# driftfile: "/lustre/or-hydra/cades-arm/proj-shared/iclass/cacti/radar_processing/taranis_corcsapr2cfr_advectionM1.c1/csapr2_500m_advection_full_campaign.nc"
# Terrain file 
terrain_file: "/global/cscratch1/sd/feng045/iclass/cacti/arm/csapr/corgridded_terrain.c0/CSAPR2_Taranis_Gridded_500m.Terrain_RangeMask.nc"
