---
# Cold pool tracking configuration file

# Identify features to track
run_idfeature: True
# Track single consecutive feature files
run_tracksingle: True
# Run tracking for all files
run_gettracks: True
# Calculate feature statistics
run_trackstats: True
# Link merge/split tracks
run_mergesplit: True
# Map tracking to pixel files
run_mapfeature: True

# Start/end date and time
startdate: '20000130.0000'
enddate: '20000201.0000'

# Parallel processing set up
# run_parallel: 1 (local cluster), 2 (Dask MPI)
run_parallel: 1
nprocesses: 64  # Number of processors to use if run_parallel=1
dask_tmp_dir: '/tmp'  # Dask temporary directory if run_parallel=1
timeout: 360  # [seconds] Dask timeout limit

databasename: buoyancy_
# Specify date/time string format in the file name
# E.g., radar_20181101.011503.nc --> yyyymodd.hhmmss
# E.g., wrfout_2018-11-01_01:15:00 --> yyyy-mo-dd_hh:mm:ss
time_format: 'yyyy-mo-ddThh-mm-ss'
# Input files directory
clouddata_path: '/pscratch/sd/p/paccini/temp/output_pinacles/buoyancy_10min/'
# Working directory for the tracking data
root_path: '/pscratch/sd/w/wcmca1/PINACLES/rce/1km/coldpool/'
# Working sub-directory names
tracking_path_name: 'tracking'
stats_path_name: 'stats'
pixel_path_name: 'cptracking'

# Specify types of feature being tracked
# This adds additional feature-specific statistics to be computed
feature_type: 'coldpool'

# Specify data structure
datatimeresolution: 0.16667     # hours
pixel_radius: 1.0      # km
time_dimname: 'time'
x_dimname: 'X'
y_dimname: 'Y'
z_dimname: 'Z'
time_coordname: 'time'
x_coordname: 'X'
y_coordname: 'Y'
z_coordname: 'Z'
field_varname: 'buoyancy'

# Feature detection parameters
label_method: 'skimage.watershed'
# Buoyancy parameters
buoy_thresh: -0.005  # [m/s^2]
min_cp_depth: 400.  # [m]
buoy_smooth_sigma: 1.5  # Gaussian smoothing sigma for cold pool intensity
# peak_local_max parameters
plm_min_distance: 20   # min_distance - distance buffer between maxima; num grid points
plm_exclude_border: 5   # exclude_border - distance buffer between maxima and the domain sides; num grid points
plm_threshold_abs: 0   # threshold_abs - minimum magnitude required to define a maxima
# watershed parameters
cont_thresh: 1.4142   # contour defining outermost of flood-filled object area
compa: 0    #"compactness factor" - (how much you'll let a flood fill spread into a neighbor's domain.)
min_size: 4  # min number of grids for a cold pool feature

# Tracking parameters
timegap: 1.0           # hour
othresh: 0.5           # overlap percentage threshold
maxnclouds: 1000       # Maximum number of features in one snapshot
nmaxlinks: 50          # Maximum number of overlaps that any single feature can be linked to
duration_range: [2, 500]   # A vector [minlength,maxlength] to specify the duration range for the tracks
# Flag to remove short-lived tracks [< min(duration_range)] that are not mergers/splits with other tracks
# 0:keep all tracks; 1:remove short tracks
remove_shorttracks: 1
# Set this flag to 1 to write a dense (2D) trackstats netCDF file
# Note that for datasets with lots of tracks, the memory consumption could be very large
trackstats_dense_netcdf: 1
# Minimum time difference threshold to match track stats with cloudid pixel files
match_pixel_dt_thresh: 60.0  # seconds

# Link merge/split parameters to main tracks
maintrack_area_thresh: 78.0  # [km^2] Main track area threshold
maintrack_lifetime_thresh: 0.5  # [hour] Main track duration threshold
split_duration: 0.3  # [hour] Split tracks <= this length is linked to the main tracks
merge_duration: 0.3  # [hour] Merge tracks <= this length is linked to the main tracks

# Define tracked feature variable names
feature_varname: 'feature_number'
nfeature_varname: 'nfeatures'
featuresize_varname: 'npix_feature'

# Track statistics output file dimension names
tracks_dimname: 'tracks'
times_dimname: 'times'
fillval: -9999
# Output file base names
finalstats_filebase: 'trackstats_final_'
pixeltracking_filebase: 'cptracks_'