---
# Global GPM based tracking configuration file

# Processing configuration to use:
processing_config: "global_gpm_mcs_processing_config.yml"

# Processing steps:
# Maybe worth nesting these in sets of dictionaries
run_idclouds : true  # Segment and identify cloud systems
run_tracksingle : true  # Track single consecutive cloudid files
run_gettracks : true  # Run trackig for all files
run_finalstats : true  # Calculate final statistics
run_identifymcs : true  # Isolate MCSs
run_matchpf : true  # Identify precipitation features with MCSs
run_robustmcs : true  # Filter potential mcs cases using nmq radar variables
run_labelmcs : true  # Create maps of MCSs

# Cores, parallel, etc
#run_parallel: 1
#nprocesses : 32  # Number of processors to use if run_parallel is set to 1
run_parallel: 0
nprocesses : 1  # Number of processors to use if run_parallel is set to 1

startdate: '20150101.0000'
enddate: '20160101.2300'

input_data_directory: "data_in/"
landmask_filename: "IMERG_landmask_global.nc"


